### ISSUE TITLE
self reference to "more documentation"

### ISSUE THREAD

**Issue by Harm-Olthof** [metadata101/iso19139.nl.services.1.2.1#7]
The link to "more documentation" is a link to this project:
https://github.com/metadata101/iso19139.nl.services.1.2.1
Logically it cannot contain "more" documentation....

**Comment by pvgenuchten** [comment]
thank you for the observation @Harm-Olthof, I think a link to https://github.com/metadata101/iso19139.nl.geografie.1.3.1/wiki was intended, let me update the readme
